# """Long Variables for Testing"""
import html_parser
import player_rater
import player_creator

# TEAM_DICT = html_parser.get_single_yahoo_team(LEAGUE_NO, "MachadoAboutNothing")
TEAM_DICT = {'TEAM_NAME': 'MachadoAboutNothing', 'TEAM_NUMBER': '1',
             'ROSTER': ['Kurt Suzuki', 'Carlos Santana', 'Trea Turner', 'Anthony Rendon',
                        'Manny Machado', 'Adam Duvall', 'Scott Schebler', 'Nelson Cruz',
                        'Tommy Pham', 'Kyle Seager', 'Melky Cabrera', 'Chris Devenski',
                        'Matt Shoemaker', 'Raisel Iglesias', 'Kenley Jansen', 'Tony Watson',
                        'Addison Reed', 'Kenta Maeda', 'Dallas Keuchel', 'Bryce Harper',
                        'Domingo Santana', 'Randal Grichuk', 'Andrew McCutchen', 'Amed Rosario',
                        'Victor Robles', 'Ivan Nova', 'Tanner Roark', 'Felix Hernandez',
                        'JA Happ']}

# TEAM_LIST = html_parser.yahoo_teams(LEAGUE_NO)
TEAM_LIST = [{'TEAM_NAME': 'MachadoAboutNothing', 'TEAM_NUMBER': '1',
              'ROSTER': ['Russell Martin', 'Carlos Santana', 'Trea Turner', 'Anthony Rendon',
                         'Manny Machado', 'Bryce Harper', 'Nelson Cruz', 'Shin-soo Choo',
                         'Andrew McCutchen', 'Kyle Seager', 'Adam Duvall', 'Brad Peacock',
                         'JA Happ', 'Raisel Iglesias', 'Kenley Jansen', 'Chris Devenski',
                         'Addison Reed', 'Sean Doolittle', 'Brad Hand', 'Scott Schebler',
                         'Eric Young Jr', 'Domingo Santana', 'Marcus Semien', 'Amed Rosario',
                         'Victor Robles', 'Ivan Nova', 'Felix Hernandez', 'Dallas Keuchel',
                         'Matt Shoemaker']},
             {'TEAM_NAME': 'Big Sack', 'TEAM_NUMBER': '2',
              'ROSTER': ['Gary Sanchez', 'Paul Goldschmidt', 'DJ LeMahieu', 'Evan Longoria',
                         'Corey Seager', 'Aaron Judge', 'Khris Davis', 'Steven Souza Jr',
                         'Mitch Haniger', 'Mark Trumbo', 'Yoenis Cespedes', 'Jacob Faria',
                         'Jake Odorizzi', 'Ken Giles', 'Brandon Maurer', 'Greg Holland',
                         'Archie Bradley', 'Koda Glover', 'Mike Montgomery', 'Byron Buxton',
                         'Alex Bregman', 'Ryan Braun', 'Rhys Hoskins', 'Jameson Taillon',
                         'Jeff Hoffman', 'Lance McCullers Jr', 'Vince Velasquez',
                         'Cole Hamels', 'Jose De Leon']},
             {'TEAM_NAME': 'Crow Ned', 'TEAM_NUMBER': '3',
              'ROSTER': ['Manny Pina', 'Justin Bour', 'Ian Kinsler', 'Jose Ramirez',
                         'Dansby Swanson', 'Corey Dickerson', 'Christian Yelich',
                         'Ender Inciarte', 'Danny Valencia', 'Dee Gordon', 'Matt Wieters',
                         'Rick Porcello', 'Jon Lester', 'Seung Hwan Oh', 'Wade Davis',
                         'Steve Cishek', 'Anthony Swarzak', 'Jason Vargas', 'Felipe Rivero',
                         'Nolan Arenado', 'Charlie Blackmon', 'Ben Zobrist', 'Freddie Freeman',
                         'Tyler Naquin', 'Michael Pineda', 'Zack Greinke', 'Sean Newcomb',
                         'Michael Kopech']},
             {'TEAM_NAME': "Betances' Chances", 'TEAM_NUMBER': '4',
              'ROSTER': ['Buster Posey', 'Eric Hosmer', 'Brandon Drury', 'Todd Frazier',
                         'Addison Russell', 'Lorenzo Cain', 'Keon Broxton', 'Ian Happ',
                         'Kyle Schwarber', 'Logan Morrison', 'Brandon Belt', 'Jake Arrieta',
                         'Gerrit Cole', 'Dellin Betances', 'Hector Neris', 'Blake Parker',
                         'Derek Law', 'AJ Ramos', 'Matt Barnes', 'Max Kepler', 'Lewis Brinson',
                         'Brian Dozier', 'Aaron Hicks', 'AJ Pollock', 'Eloy Jimenez',
                         'Aaron Nola', 'Noah Syndergaard', 'Julio Urias']},
             {'TEAM_NAME': '10-Day DL', 'TEAM_NUMBER': '5',
              'ROSTER': ['JT Realmuto', 'Jose Abreu', 'Jason Kipnis', 'Mike Moustakas',
                         'Carlos Correa', 'JD Martinez', 'Matt Adams', 'Kendrys Morales',
                         'Jackie Bradley Jr', 'Ryan Zimmerman', 'Michael Conforto',
                         'Steven Matz', 'Zack Wheeler', 'Mark Melancon', 'Cody Allen',
                         'Santiago Casilla', 'Chris Archer', 'Sonny Gray', 'Alex Meyer',
                         'David Peralta', 'Aaron Altherr', 'Stephen Piscotty', 'Greg Bird',
                         'Yoan Moncada', 'David Price', 'Ervin Santana', 'Ariel Miranda',
                         'Jon Gray', 'Brent Honeywell']},
             {'TEAM_NAME': 'NK Sluggers', 'TEAM_NUMBER': '6',
              'ROSTER': ['Evan Gattis', 'Mark Reynolds', 'Matt Carpenter', 'Justin Turner',
                         'Trevor Story', 'Justin Upton', 'Mookie Betts', 'Andrew Benintendi',
                         'Brett Gardner', 'Trey Mancini', 'Jedd Gyorko', 'Dinelson Lamet',
                         'Jordan Montgomery', 'Fernando Rodney', 'Matt Albers',
                         'Trevor Rosenthal', 'Clayton Kershaw', 'Drew Storen', 'James Paxton',
                         'Michael Brantley', 'Kevin Pillar', 'Aledmys Diaz', 'Eugenio Suarez',
                         'Stephen Strasburg', 'Kyle Hendricks', 'Madison Bumgarner',
                         'Drew Smyly']},
             {'TEAM_NAME': 'Yo Mammas RustyKuntz', 'TEAM_NUMBER': '7',
              'ROSTER': ['Salvador Perez', 'Albert Pujols', 'Dustin Pedroia', 'Maikel Franco',
                         'Jonathan Villar', 'Matt Kemp', 'Curtis Granderson', 'Chris Owings',
                         'Marwin Gonzalez', 'Matt Holliday', 'Jason Heyward', 'Jerad Eickhoff',
                         'Yu Darvish', 'Alex Colome', 'Roberto Osuna', 'Adam Wainwright',
                         'Clayton Richard', 'Miguel Gonzalez', 'Chris Tillman', 'Carlos Beltran',
                         'Carlos Gonzalez', 'AJ Reed', 'Jason Hammel', 'Andrew Miller',
                         'Carlos Carrasco', 'Edinson Volquez', 'Rich Hill']},
             {'TEAM_NAME': "R.Odor's PunchOut!!!", 'TEAM_NUMBER': '8',
              'ROSTER': ['Willson Contreras', 'Anthony Rizzo', 'Rougned Odor', 'Ryon Healy',
                         'Francisco Lindor', 'Hunter Renfroe', 'Billy Hamilton', 'Kole Calhoun',
                         'Josh Bell', 'Adrian Beltre', 'Joey Gallo', 'Jacob deGrom', 'Mike Leake',
                         'Jim Johnson', 'Brandon Kintzler', 'Brad Brach', 'Matt Bush',
                         'Marcus Stroman', 'Enny Romero', 'Derek Fisher', 'Xander Bogaerts',
                         'Elvis Andrus', 'Starling Marte', 'Yasmany Tomas', 'Rafael Devers',
                         "Tyler O'Neill", 'Johnny Cueto', 'Zack Godley']},
             {'TEAM_NAME': 'The Southsiders', 'TEAM_NUMBER': '9',
              'ROSTER': ['Alex Avila', 'Daniel Murphy', 'Jose Altuve', 'Miguel Sano',
                         'Hernan Perez', 'Avisail Garcia', 'Giancarlo Stanton', 'Ian Desmond',
                         'Cameron Maybin', 'Bradley Zimmer', 'Brian McCann', 'Chris Sale',
                         'Gio Gonzalez', 'David Robertson', 'Justin Wilson', 'Bud Norris',
                         'Pat Neshek', 'Adam Ottavino', 'Alex Wood', 'Wil Myers', 'Jean Segura',
                         'Adam Eaton', 'Junior Guerra', 'Jose Quintana', 'Zach Britton',
                         'Mike Fiers', 'Carlos Rodon', 'Lucas Giolito', 'Reynaldo Lopez']},
             {'TEAM_NAME': 'Thome Dont Play Dat', 'TEAM_NUMBER': '10',
              'ROSTER': ['Jonathan Lucroy', 'Miguel Cabrera', 'Robinson Cano', 'Josh Donaldson',
                         'Troy Tulowitzki', 'Whit Merrifield', 'Nomar Mazara', 'Adam Jones',
                         'Eric Thames', 'Jonathan Schoop', 'Hunter Pence', 'Max Scherzer',
                         'Jimmy Nelson', 'Francisco Rodriguez', 'Marco Estrada', 'Alex Cobb',
                         'Brandon McCarthy', 'Zach Davies', 'Yasiel Puig', 'Chris Taylor',
                         'Welington Castillo', 'Hanley Ramirez', 'Jayson Werth', 'Wilson Ramos',
                         'Franklin Barreto', 'Chase Anderson', 'Danny Duffy', 'Jeurys Familia',
                         'Mauricio Cabrera']},
             {'TEAM_NAME': 'WHIPmyHairBackNForth', 'TEAM_NUMBER': '11',
              'ROSTER': ['Mike Zunino', 'Joey Votto', 'Jed Lowrie', 'Travis Shaw',
                         'Javier Baez', 'Marcell Ozuna', 'Jay Bruce', 'Dexter Fowler',
                         'Carlos Gomez', 'Kris Bryant', 'Justin Smoak', 'Masahiro Tanaka',
                         'Francisco Liriano', 'Edwin Diaz', 'Kelvin Herrera', 'Carlos Martinez',
                         'Corey Knebel', 'Tommy Kahnle', 'Julio Teheran', 'Jose Peraza',
                         'Yonder Alonso', 'Zack Cozart', 'Mike Trout', 'David Dahl',
                         'Jeimer Candelario', 'Gleyber Torres', 'Jeff Samardzija', 'Lance Lynn',
                         'CC Sabathia']},
             {'TEAM_NAME': 'Yates Dynasty v12.0', 'TEAM_NUMBER': '12',
              'ROSTER': ['Yasmani Grandal', 'Edwin Encarnacion', 'Starlin Castro', 'Jake Lamb',
                         'Eduardo Nunez', 'George Springer', 'Gregory Polanco', 'Cody Bellinger',
                         'Jose Bautista', 'Tommy Joseph', 'Mallex Smith', 'Dylan Bundy',
                         'Corey Kluber', 'Craig Kimbrel', 'Will Harris', 'Jose Berrios',
                         'Luis Severino', 'Justin Verlander', 'Aroldis Chapman', 'Odubel Herrera',
                         'Joc Pederson', 'Chris Davis', 'Ryan Schimpf', 'Austin Meadows',
                         'Dan Straily', 'Robbie Ray', 'Sean Manaea', 'Taijuan Walker',
                         'Aaron Sanchez']}]

# LEAGUE_SETTINGS = html_parser.get_league_settings(5091)
LEAGUE_SETTINGS = {'Draft Type:': 'Live Auction Draft',
                   'Post Draft Players:': 'Follow Waiver Rules',
                   'New Players Become Available:': 'As soon as Yahoo adds them',
                   'Max Teams:': '12', 'Send unjoined players email reminders:': 'Yes',
                   "Can't Cut List Provider:": 'Yahoo Sports', 'Auto-renew Enabled:': 'Yes',
                   'Max Trades for Entire Season': 'No maximum',
                   'Cash League Settings:': 'Not a cash league', 'Trade Reject Time:': '2',
                   'Keeper Settings:': 'Yes, enable Keeper League Management tools',
                   'League Name:': 'Grays Sports Almanac', 'Roster Changes:': 'Daily - Today',
                   'Keeper Deadline Date:': 'Sun Mar 26 12:00am PDT',
                   'Batters Stat Categories:': 'Runs (R), Home Runs (HR), Runs Batted In (RBI), Stolen Bases (SB), On-base + Slugging Percentage (OPS)',
                   'Invite Permissions:': 'Commissioner Only',
                   'Roster Positions:': 'C, 1B, 2B, 3B, SS, OF, OF, OF, OF, Util, Util, SP, SP, RP, RP, P, P, P, P, BN, BN, BN, BN, BN, BN, DL, DL, NA, NA',
                   'Draft Time:': 'Sat Apr 1 9:00am PDT', 'Trade Review:': 'Commissioner',
                   'Max Games Played:': '162', 'Trade End Date:': 'August 13, 2017',
                   'Max Innings Pitched:': '1500', 'Scoring Type:': 'Rotisserie',
                   'Max Acquisitions for Entire Season:': 'No maximum',
                   'Allow Draft Pick Trades:': 'No', 'Waiver Mode:': 'Standard',
                   'Allow injured players from waivers or free agents to be added directly to IR:': 'No',
                   'League ID#:': '5091', 'Waiver Type:': 'FAAB w/ Continual rolling list tiebreak',
                   'Waiver Time:': '2 days',
                   'Pitchers Stat Categories:': 'Wins (W), Saves (SV), Strikeouts (K), Earned Run Average (ERA), (Walks + Hits)/ Innings Pitched (WHIP)',
                   'Custom League URL:': 'https://baseball.fantasysports.yahoo.com/league/grayssportsalmanac',
                   'Player Universe:': 'All baseball', 'Make League Publicly Viewable:': 'Yes',
                   'Start Scoring on:': 'Sunday, Apr 2'}

# LEAGUE_POS_DICT = html_parser.split_league_pos_types(LEAGUE_SETTINGS["Roster Positions:"])
LEAGUE_POS_DICT = {'Pitching POS': ['SP', 'SP', 'RP', 'RP', 'P', 'P', 'P', 'P'],
                   'Bench POS': ['BN', 'BN', 'BN', 'BN', 'BN', 'BN'],
                   'DL POS': ['DL', 'DL'],
                   'Batting POS': ['C', '1B', '2B', '3B', 'SS', 'OF', 'OF', 'OF',
                                   'OF', 'Util', 'Util'],
                   'NA POS': ['NA', 'NA']}

# CURRENT_STANDINGS = html_parser.get_standings(LEAGUE_NO, TEAM_COUNT)
CURRENT_STANDINGS = [{'StatsTotalGP': '549', 'StatsOPS': '.840', 'StatsERA': '3.66',
                      'PointsSB': '7', 'StatsRBI': '305', 'StatsR': '338', 'PointsSV': '12',
                      'StatsWHIP': '1.19', 'StatsHR': '105', 'PointsTotal': '97', 'StatsSB': '37',
                      'PointsTeam': 'Big Sack', 'StatsIP': '415.1', 'PointsRBI': '10',
                      'PointsWHIP': '9', 'StatsK': '405', 'PointsOPS': '12', 'StatsSV': '54',
                      'StatsTeam': 'Big Sack', 'PointsR': '11', 'StatsW': '26', 'PointsW': '6',
                      'PointsK': '8', 'PointsRank': '1', 'PointsERA': '10', 'StatsRank': '1',
                      'PointsHR': '12'},
                     {'StatsTotalGP': '563', 'StatsOPS': '.762', 'StatsERA': '3.56',
                      'PointsSB': '12', 'StatsRBI': '298', 'StatsR': '307', 'PointsSV': '11',
                      'StatsWHIP': '1.22', 'StatsHR': '94', 'PointsTotal': '89', 'StatsSB': '62',
                      'PointsTeam': "R.Odor's PunchOut!!!", 'StatsIP': '444.1', 'PointsRBI': '8',
                      'PointsWHIP': '8', 'StatsK': '389', 'PointsOPS': '4', 'StatsSV': '43',
                      'StatsTeam': "R.Odor's PunchOut!!!", 'PointsR': '9', 'StatsW': '33',
                      'PointsW': '11', 'PointsK': '4', 'PointsRank': '2', 'PointsERA': '12',
                      'StatsRank': '2', 'PointsHR': '10'},
                     {'StatsTotalGP': '533', 'StatsOPS': '.793', 'StatsERA': '3.76',
                      'PointsSB': '6', 'StatsRBI': '304', 'StatsR': '272', 'PointsSV': '10',
                      'StatsWHIP': '1.17', 'StatsHR': '92', 'PointsTotal': '87', 'StatsSB': '33',
                      'PointsTeam': 'MachadoAboutNothing', 'StatsIP': '464.2', 'PointsRBI': '9',
                      'PointsWHIP': '12', 'StatsK': '425', 'PointsOPS': '9', 'StatsSV': '38',
                      'StatsTeam': 'MachadoAboutNothing', 'PointsR': '3', 'StatsW': '38',
                      'PointsW': '12', 'PointsK': '9', 'PointsRank': '3', 'PointsERA': '8',
                      'StatsRank': '3', 'PointsHR': '9'},
                     {'StatsTotalGP': '562', 'StatsOPS': '.791', 'StatsERA': '3.78',
                      'PointsSB': '8.5', 'StatsRBI': '270', 'StatsR': '341', 'PointsSV': '5',
                      'StatsWHIP': '1.24', 'StatsHR': '84', 'PointsTotal': '78.5', 'StatsSB': '41',
                      'PointsTeam': 'Crow Ned', 'StatsIP': '507.2', 'PointsRBI': '3',
                      'PointsWHIP': '7', 'StatsK': '498', 'PointsOPS': '8', 'StatsSV': '21',
                      'StatsTeam': 'Crow Ned', 'PointsR': '12', 'StatsW': '31', 'PointsW': '10',
                      'PointsK': '12', 'PointsRank': '4', 'PointsERA': '7', 'StatsRank': '4',
                      'PointsHR': '6'},
                     {'StatsTotalGP': '546', 'StatsOPS': '.827', 'StatsERA': '3.79',
                      'PointsSB': '8.5', 'StatsRBI': '311', 'StatsR': '320', 'PointsSV': '8',
                      'StatsWHIP': '1.28', 'StatsHR': '83', 'PointsTotal': '75', 'StatsSB': '41',
                      'PointsTeam': 'The Southsiders', 'StatsIP': '418.0', 'PointsRBI': '11',
                      'PointsWHIP': '4', 'StatsK': '447', 'PointsOPS': '10', 'StatsSV': '28',
                      'StatsTeam': 'The Southsiders', 'PointsR': '10', 'StatsW': '22',
                      'PointsW': '3', 'PointsK': '10', 'PointsRank': '5', 'PointsERA': '6',
                      'StatsRank': '5', 'PointsHR': '4.5'},
                     {'StatsTotalGP': '535', 'StatsOPS': '.838', 'StatsERA': '4.17',
                      'PointsSB': '3', 'StatsRBI': '312', 'StatsR': '301', 'PointsSV': '7',
                      'StatsWHIP': '1.35', 'StatsHR': '101', 'PointsTotal': '66.5', 'StatsSB': '26',
                      'PointsTeam': 'WHIPmyHairBackNForth', 'StatsIP': '410.1', 'PointsRBI': '12',
                      'PointsWHIP': '1', 'StatsK': '394', 'PointsOPS': '11', 'StatsSV': '24',
                      'StatsTeam': 'WHIPmyHairBackNForth', 'PointsR': '8', 'StatsW': '23',
                      'PointsW': '5', 'PointsK': '6.5', 'PointsRank': '6', 'PointsERA': '2',
                      'StatsRank': '6', 'PointsHR': '11'},
                     {'StatsTotalGP': '556', 'StatsOPS': '.763', 'StatsERA': '3.89',
                      'PointsSB': '5', 'StatsRBI': '276', 'StatsR': '297', 'PointsSV': '4',
                      'StatsWHIP': '1.27', 'StatsHR': '91', 'PointsTotal': '62.5', 'StatsSB': '28',
                      'PointsTeam': 'Yates Dynasty v12.0', 'StatsIP': '453.2', 'PointsRBI': '5',
                      'PointsWHIP': '5', 'StatsK': '494', 'PointsOPS': '5', 'StatsSV': '20',
                      'StatsTeam': 'Yates Dynasty v12.0', 'PointsR': '7', 'StatsW': '28',
                      'PointsW': '7.5', 'PointsK': '11', 'PointsRank': '7', 'PointsERA': '5',
                      'StatsRank': '7', 'PointsHR': '8'},
                     {'StatsTotalGP': '541', 'StatsOPS': '.781', 'StatsERA': '3.59',
                      'PointsSB': '1', 'StatsRBI': '287', 'StatsR': '278', 'PointsSV': '9',
                      'StatsWHIP': '1.17', 'StatsHR': '89', 'PointsTotal': '62', 'StatsSB': '14',
                      'PointsTeam': '10-Day DL', 'StatsIP': '366.0', 'PointsRBI': '7',
                      'PointsWHIP': '11', 'StatsK': '351', 'PointsOPS': '6', 'StatsSV': '31',
                      'StatsTeam': '10-Day DL', 'PointsR': '5', 'StatsW': '22', 'PointsW': '3',
                      'PointsK': '2', 'PointsRank': '8', 'PointsERA': '11', 'StatsRank': '8',
                      'PointsHR': '7'},
                     {'StatsTotalGP': '541', 'StatsOPS': '.755', 'StatsERA': '3.68',
                      'PointsSB': '10', 'StatsRBI': '263', 'StatsR': '287', 'PointsSV': '2.5',
                      'StatsWHIP': '1.19', 'StatsHR': '81', 'PointsTotal': '58', 'StatsSB': '45',
                      'PointsTeam': 'NK Sluggers', 'StatsIP': '386.2', 'PointsRBI': '2',
                      'PointsWHIP': '10', 'StatsK': '391', 'PointsOPS': '3', 'StatsSV': '18',
                      'StatsTeam': 'NK Sluggers', 'PointsR': '6', 'StatsW': '28', 'PointsW': '7.5',
                      'PointsK': '5', 'PointsRank': '9', 'PointsERA': '9', 'StatsRank': '9',
                      'PointsHR': '3'},
                     {'StatsTotalGP': '526', 'StatsOPS': '.783', 'StatsERA': '4.04',
                      'PointsSB': '2', 'StatsRBI': '284', 'StatsR': '271', 'PointsSV': '1',
                      'StatsWHIP': '1.27', 'StatsHR': '83', 'PointsTotal': '43.5', 'StatsSB': '18',
                      'PointsTeam': 'Thome Dont Play Dat', 'StatsIP': '403.1', 'PointsRBI': '6',
                      'PointsWHIP': '6', 'StatsK': '381', 'PointsOPS': '7', 'StatsSV': '10',
                      'StatsTeam': 'Thome Dont Play Dat', 'PointsR': '2', 'StatsW': '30',
                      'PointsW': '9', 'PointsK': '3', 'PointsRank': '10', 'PointsERA': '3',
                      'StatsRank': '10', 'PointsHR': '4.5'},
                     {'StatsTotalGP': '521', 'StatsOPS': '.724', 'StatsERA': '3.92',
                      'PointsSB': '4', 'StatsRBI': '274', 'StatsR': '226', 'PointsSV': '6',
                      'StatsWHIP': '1.34', 'StatsHR': '67', 'PointsTotal': '33.5', 'StatsSB': '27',
                      'PointsTeam': 'Yo Mammas RustyKuntz', 'StatsIP': '432.0', 'PointsRBI': '4',
                      'PointsWHIP': '2', 'StatsK': '394', 'PointsOPS': '1', 'StatsSV': '23',
                      'StatsTeam': 'Yo Mammas RustyKuntz', 'PointsR': '1', 'StatsW': '22',
                      'PointsW': '3', 'PointsK': '6.5', 'PointsRank': '11', 'PointsERA': '4',
                      'StatsRank': '11', 'PointsHR': '2'},
                     {'StatsTotalGP': '546', 'StatsOPS': '.741', 'StatsERA': '4.31',
                      'PointsSB': '11', 'StatsRBI': '202', 'StatsR': '273', 'PointsSV': '2.5',
                      'StatsWHIP': '1.31', 'StatsHR': '62', 'PointsTotal': '27.5', 'StatsSB': '58',
                      'PointsTeam': 'Stats in Binary', 'StatsIP': '329.2', 'PointsRBI': '1',
                      'PointsWHIP': '3', 'StatsK': '345', 'PointsOPS': '2', 'StatsSV': '18',
                      'StatsTeam': 'Stats in Binary', 'PointsR': '4', 'StatsW': '18',
                      'PointsW': '1', 'PointsK': '1', 'PointsRank': '12', 'PointsERA': '1',
                      'StatsRank': '12', 'PointsHR': '1'}]

FINAL_STANDINGS_PROJECTION = [{'StatsTotalGP': 1748.8826979472142, 'StatsSV': 114,
                               'StatsWHIP': 1.1635893333333331, 'StatsOPS': 0.8098177047862825,
                               'StatsERA': 3.4390466666666666, 'StatsW': 115, 'StatsK': 1417,
                               'StatsRBI': 1013, 'StatsHR': 305, 'StatsSB': 123, 'StatsR': 976,
                               'TEAM_NAME': 'MachadoAboutNothing', 'StatsIP': 1500.0},
                              {'StatsTotalGP': 783.5601173020528, 'StatsSV': 125,
                               'StatsWHIP': 1.2637962813257877, 'StatsOPS': 0.8518795027599991,
                               'StatsERA': 3.8421341956346002, 'StatsW': 70, 'StatsK': 1187,
                               'StatsRBI': 470, 'StatsHR': 149, 'StatsSB': 51, 'StatsR': 505,
                               'TEAM_NAME': 'Big Sack', 'StatsIP': 1237.0},
                              {'StatsTotalGP': 816.958944281525, 'StatsSV': 63,
                               'StatsWHIP': 1.2334894772572982, 'StatsOPS': 0.80374901096746,
                               'StatsERA': 3.6930549898167015, 'StatsW': 95, 'StatsK': 1418,
                               'StatsRBI': 421, 'StatsHR': 115, 'StatsSB': 69, 'StatsR': 504,
                               'TEAM_NAME': 'Crow Ned', 'StatsIP': 1473.0},
                              {'StatsTotalGP': 780.1906158357772, 'StatsSV': 65,
                               'StatsWHIP': 1.2771140684410645, 'StatsOPS': 0.7717008309668368,
                               'StatsERA': 3.81116349809886, 'StatsW': 75, 'StatsK': 1104,
                               'StatsRBI': 342, 'StatsHR': 113, 'StatsSB': 67, 'StatsR': 411,
                               'TEAM_NAME': "Betances' Chances", 'StatsIP': 1052.0},
                              {'StatsTotalGP': 777.6920821114369, 'StatsSV': 85,
                               'StatsWHIP': 1.2552505147563484, 'StatsOPS': 0.803140137370078,
                               'StatsERA': 3.8668977350720657, 'StatsW': 95, 'StatsK': 1403,
                               'StatsRBI': 429, 'StatsHR': 133, 'StatsSB': 18, 'StatsR': 418,
                               'TEAM_NAME': '10-Day DL', 'StatsIP': 1457.0},
                              {'StatsTotalGP': 759.1642228739003, 'StatsSV': 42,
                               'StatsWHIP': 1.174179743223966, 'StatsOPS': 0.7570881764967071,
                               'StatsERA': 3.5260413694721815, 'StatsW': 100, 'StatsK': 1462,
                               'StatsRBI': 381, 'StatsHR': 112, 'StatsSB': 57, 'StatsR': 405,
                               'TEAM_NAME': 'NK Sluggers', 'StatsIP': 1402.0},
                              {'StatsTotalGP': 721.0205278592375, 'StatsSV': 66,
                               'StatsWHIP': 1.3247000000000002, 'StatsOPS': 0.7433844394702055,
                               'StatsERA': 4.065102666666667, 'StatsW': 89, 'StatsK': 1360,
                               'StatsRBI': 372, 'StatsHR': 95, 'StatsSB': 36, 'StatsR': 318,
                               'TEAM_NAME': 'Yo Mammas RustyKuntz', 'StatsIP': 1500.0},
                              {'StatsTotalGP': 803.8856304985337, 'StatsSV': 109,
                               'StatsWHIP': 1.2234583020285499, 'StatsOPS': 0.752076571019109,
                               'StatsERA': 3.645528925619836, 'StatsW': 90, 'StatsK': 1180,
                               'StatsRBI': 418, 'StatsHR': 126, 'StatsSB': 73, 'StatsR': 427,
                               'TEAM_NAME': "R.Odor's PunchOut!!!", 'StatsIP': 1331.0},
                              {'StatsTotalGP': 744, 'StatsSV': 86,
                               'StatsWHIP': 1.2541253333333338, 'StatsOPS': 0.849,
                               'StatsERA': 3.642506, 'StatsW': 91, 'StatsK': 1563,
                               'StatsRBI': 430, 'StatsHR': 122, 'StatsSB': 65, 'StatsR': 439,
                               'TEAM_NAME': 'The Southsiders', 'StatsIP': 1500.0},
                              {'StatsTotalGP': 754.7126099706745, 'StatsSV': 25,
                               'StatsWHIP': 1.2710945853324196, 'StatsOPS': 0.7921607432436983,
                               'StatsERA': 3.947032899246059, 'StatsW': 93, 'StatsK': 1377,
                               'StatsRBI': 408, 'StatsHR': 122, 'StatsSB': 26, 'StatsR': 388,
                               'TEAM_NAME': 'Thome Dont Play Dat', 'StatsIP': 1459.0},
                              {'StatsTotalGP': 758.4662756598241, 'StatsSV': 85,
                               'StatsWHIP': 1.3029653333333335, 'StatsOPS': 0.8681736130353572,
                               'StatsERA': 4.010556000000001, 'StatsW': 90, 'StatsK': 1485,
                               'StatsRBI': 456, 'StatsHR': 163, 'StatsSB': 37, 'StatsR': 441, 'TEAM_NAME': 'WHIPmyHairBackNForth', 'StatsIP': 1500.0}, {'StatsTotalGP': 795.0029325513198, 'StatsSV': 68, 'StatsWHIP': 1.212126666666667, 'StatsOPS': 0.7922814952426378, 'StatsERA': 3.552646666666667, 'StatsW': 106, 'StatsK': 1600, 'StatsRBI': 422, 'StatsHR': 144, 'StatsSB': 39, 'StatsR': 457, 'TEAM_NAME': 'Yates Dynasty v12.0', 'StatsIP': 1500.0}]
